const projects = [
  {name:'VideoBuilder', status:'active', statusText:'В розробці', type:'Java', desc:'Minecraft-мод для сканування відео та реконструкції світу.', url:'https://github.com/IT11GG/VideoBuilder', image:'https://images.unsplash.com/photo-1612287230202-1ff1d85d1bdf?auto=format&fit=crop&w=900&q=80'},
  {name:'PulseArcade', status:'active', statusText:'В розробці', type:'Kotlin', desc:'Мобільний простір для стримінгу та ігрового контенту.', url:'https://github.com/IT11GG/PulseArcade', image:'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=900&q=80'},
  {name:'PulseLinux', status:'active', statusText:'В розробці', type:'C / OS', desc:'Операційна система з фокусом на продуктивність та OLED.', url:'https://github.com/IT11GG/PulseLinux', image:'https://images.unsplash.com/photo-1629654297299-c8506221ca97?auto=format&fit=crop&w=900&q=80'},
  {name:'Documental-site', status:'active', statusText:'Живий', type:'JavaScript', desc:'Вебдосвід для документального контенту.', url:'https://github.com/IT11GG/Documental-site', image:'https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&w=900&q=80'},
  {name:'AquaClient', status:'archive', statusText:'Архів', type:'Java', desc:'Клієнтський експеримент у світі Minecraft.', url:'https://github.com/IT11GG/AquaClient', image:'https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=900&q=80'},
  {name:'zombi-game', status:'archive', statusText:'Архів', type:'JavaScript', desc:'Невелика браузерна гра з атмосферою виживання.', url:'https://github.com/IT11GG/zombi-game', image:'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=900&q=80'},
  {name:'MS-Rewards-Farmer', status:'archive', statusText:'Архів', type:'Python', desc:'Автоматизація рутинних задач через Selenium.', url:'https://github.com/IT11GG/MS-Rewards-Farmer', image:'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=900&q=80'},
  {name:'mebli_lviv', status:'archive', statusText:'Архів', type:'HTML', desc:'Сайт меблевого проєкту.', url:'https://github.com/IT11GG/mebli_lviv', image:'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=900&q=80'},
  {name:'randomizer', status:'archive', statusText:'Архів', type:'Web', desc:'Сайт, побудований навколо випадковості.', url:'https://github.com/IT11GG/randomizer', image:'https://images.unsplash.com/photo-1519608487953-e999c86e7455?auto=format&fit=crop&w=900&q=80'},
  {name:'DrasticDev', status:'archive', statusText:'Архів', type:'Dev', desc:'Експерименти та нотатки розробника.', url:'https://github.com/IT11GG/DrasticDev', image:'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=900&q=80'},
  {name:'Scriptdeadrails', status:'archive', statusText:'Архів', type:'Script', desc:'Скрипти та прототипи для ігрових ідей.', url:'https://github.com/IT11GG/Scriptdeadrails', image:'https://images.unsplash.com/photo-1535223289827-42f1e9919769?auto=format&fit=crop&w=900&q=80'},
  {name:'clickgui', status:'archive', statusText:'Архів', type:'Java', desc:'Дослідження інтерфейсів та взаємодії.', url:'https://github.com/IT11GG/clickgui', image:'https://images.unsplash.com/photo-1551650975-87deedd944c3?auto=format&fit=crop&w=900&q=80'},
  {name:'Nickname', status:'archive', statusText:'Архів', type:'HTML', desc:'Один із перших вебекспериментів.', url:'https://github.com/IT11GG/Nickname', image:'https://images.unsplash.com/photo-1558655146-d09347e92766?auto=format&fit=crop&w=900&q=80'},
  {name:'Nickname1', status:'archive', statusText:'Архів', type:'HTML', desc:'Продовження серії ранніх прототипів.', url:'https://github.com/IT11GG/Nickname1', image:'https://images.unsplash.com/photo-1559028012-481c04fa702d?auto=format&fit=crop&w=900&q=80'},
  {name:'Sovet_hayday', status:'archive', statusText:'Архів', type:'HTML', desc:'Сторінка, що зберегла свою історію.', url:'https://github.com/IT11GG/Sovet_hayday', image:'https://images.unsplash.com/photo-1499750310107-5fef28a66643?auto=format&fit=crop&w=900&q=80'},
  {name:'comfortable-sofa', status:'archive', statusText:'Архів', type:'Web', desc:'Вебсторінка з каталоговим підходом.', url:'https://github.com/IT11GG/index', image:'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=900&q=80'},
  {name:'arduino', status:'archive', statusText:'Архів', type:'Hardware', desc:'Перші кроки в роботі з залізом.', url:'https://github.com/IT11GG/arduino', image:'https://images.unsplash.com/photo-1553406830-ef2513450d76?auto=format&fit=crop&w=900&q=80'},
  {name:'123', status:'archive', statusText:'Архів', type:'Experiment', desc:'Маленький експеримент без зайвих пояснень.', url:'https://github.com/IT11GG/123', image:'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=900&q=80'},
  {name:'maksik', status:'archive', statusText:'Архів', type:'HTML', desc:'Персональний сайт із власним характером.', url:'https://github.com/IT11GG/maksik', image:'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=900&q=80'},
  {name:'1 / 111111', status:'archive', statusText:'Архів', type:'Experiment', desc:'Колекція ранніх тестів та ідей.', url:'https://github.com/IT11GG/111111', image:'https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=900&q=80'}
];
const grid=document.querySelector('#project-grid'), empty=document.querySelector('#empty'), search=document.querySelector('#search'); let filter='all';
function render(){const q=search.value.toLowerCase();const list=projects.filter(p=>(filter==='all'||p.status===filter)&&(`${p.name} ${p.type} ${p.desc}`.toLowerCase().includes(q)));grid.innerHTML=list.map(p=>`<a class="project-card" href="${p.url}" target="_blank" rel="noreferrer"><div class="card-image" style="background-image:url('${p.image}')"></div><div class="card-body"><span class="card-status ${p.status}">${p.statusText}</span><span class="card-title">${p.name}</span><span class="card-desc">${p.desc}</span><div class="card-meta"><span>${p.type}</span><span class="card-arrow">↗</span></div></div></a>`).join('');empty.style.display=list.length?'none':'block'}
document.querySelectorAll('.filter').forEach(btn=>btn.addEventListener('click',()=>{document.querySelector('.filter.active').classList.remove('active');btn.classList.add('active');filter=btn.dataset.filter;render()}));search.addEventListener('input',render);document.querySelector('.menu-toggle').addEventListener('click',()=>document.querySelector('.nav').classList.toggle('mobile-open'));render();
